# Generated by Django 5.2.7 on 2025-10-31 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_movie_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='guest_name',
            new_name='guest',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_name',
            new_name='movie',
        ),
    ]
